export const carModels = [
    { label: 'Toyota', value: 'toyota' },
    { label: 'Ford', value: 'ford' },
    { label: 'Honda', value: 'honda' },
    { label: 'Chevrolet', value: 'chevrolet' },
    { label: 'Volkswagen', value: 'volkswagen' },
    { label: 'Nissan', value: 'nissan' },
    { label: 'BMW', value: 'bmw' },
    { label: 'Audi', value: 'audi' },
    { label: 'Hyundai', value: 'hyundai' },
    { label: 'Kia', value: 'kia' },
    { label: 'Volvo', value: 'volvo' },
    { label: 'Mazda', value: 'mazda' },
    { label: 'Subaru', value: 'subaru' },
    { label: 'Lexus', value: 'lexus' },
    { label: 'Jeep', value: 'jeep' },
    { label: 'Tesla', value: 'tesla' },
    { label: 'Porsche', value: 'porsche' },
    { label: 'Fiat', value: 'fiat' },
    { label: 'Land Rover', value: 'landrover' },
    { label: 'Chrysler', value: 'chrysler' },
    { label: 'Acura', value: 'acura' },
    { label: 'Buick', value: 'buick' },
    { label: 'Cadillac', value: 'cadillac' },
    { label: 'Dodge', value: 'dodge' },
    { label: 'Infiniti', value: 'infiniti' },
    { label: 'Jaguar', value: 'jaguar' },
    { label: 'Mini', value: 'mini' },
    { label: 'Mitsubishi', value: 'mitsubishi' },
    { label: 'Ram', value: 'ram' },
]

export const colorCars = [
    { label: 'Black', value: 'black' },
    { label: 'White', value: 'white' },
    { label: 'Silver', value: 'silver' },
    { label: 'Gray', value: 'gray' },
    { label: 'Blue', value: 'blue' },
    { label: 'Red', value: 'red' },
    { label: 'Green', value: 'green' },
    { label: 'Yellow', value: 'yellow' },
    { label: 'Orange', value: 'orange' },
    { label: 'Brown', value: 'brown' },
    { label: 'Beige', value: 'beige' },
    { label: 'Gold', value: 'gold' },
    { label: 'Purple', value: 'purple' },
    { label: 'Pink', value: 'pink' },
    { label: 'Turquoise', value: 'turquoise' },
    { label: 'Lime', value: 'lime' },
    { label: 'Teal', value: 'teal' },
    { label: 'Cyan', value: 'cyan' },
    { label: 'Magenta', value: 'magenta' },
    { label: 'Indigo', value: 'indigo' },
  ]
  
  